const { chromium } = require('playwright');
const SCRATCHPAD = 'C:/Users/kevin/AppData/Local/Temp/claude/C--Users-kevin-Documents-Dev-hotel-rayon-vert/70e85f34-b52c-4577-99e7-fbf326a1ab17/scratchpad';
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('http://localhost:5173', { waitUntil: 'networkidle', timeout: 20000 });
  await page.waitForTimeout(3500);
  await page.screenshot({ path: SCRATCHPAD + '/hero.png' });
  console.log('Hero captured');
  await page.evaluate(() => document.getElementById('chambres')?.scrollIntoView({ behavior: 'smooth' }));
  await page.waitForTimeout(2500);
  await page.screenshot({ path: SCRATCHPAD + '/rooms.png' });
  console.log('Rooms captured');
  await page.evaluate(() => document.getElementById('restaurant')?.scrollIntoView({ behavior: 'smooth' }));
  await page.waitForTimeout(2000);
  await page.screenshot({ path: SCRATCHPAD + '/restaurant.png' });
  console.log('Restaurant');
  await page.evaluate(() => document.getElementById('galerie')?.scrollIntoView({ behavior: 'smooth' }));
  await page.waitForTimeout(2000);
  await page.screenshot({ path: SCRATCHPAD + '/gallery.png' });
  console.log('Gallery');
  await browser.close();
  console.log('Done');
})();
